// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA06-ddoXskjNw0UB_M0uR9c8VbHpaHA5Q',
    appId: '1:469759282994:web:3c9e821e4b7cfe19d1d12b',
    messagingSenderId: '469759282994',
    projectId: 'social-media-424b4',
    authDomain: 'social-media-424b4.firebaseapp.com',
    storageBucket: 'social-media-424b4.firebasestorage.app',
    measurementId: 'G-SZV1W8KF15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6CGl26LRhGjJUPGexDJzqQ4WFzFtC1W8',
    appId: '1:469759282994:android:34f4b99fc5f26874d1d12b',
    messagingSenderId: '469759282994',
    projectId: 'social-media-424b4',
    storageBucket: 'social-media-424b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIAyDoa3gfq4_V4I8f8tyU_9_Ey1ayhC8',
    appId: '1:469759282994:ios:6771b15b5ebcca11d1d12b',
    messagingSenderId: '469759282994',
    projectId: 'social-media-424b4',
    storageBucket: 'social-media-424b4.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
